### ISSUE TITLE
Can we add a warning level, instead of just error or no error? 

### ISSUE THREAD

**Issue by hbrice** [FabiowQuixada/isml-linter#15]
I find it would be helpful if we could have a "warning" level like in es-lint or sass-lint. Sometimes there's too many errors on a project that we just want to be aware of them but not necessarily fix them.

**Comment by FabiowQuixada** [comment]
Hello @hbrice ,

thanks for the suggestion! Will work on that and will also add an "info" level.

Will let you know once it is published.

Thank you again,

**Comment by FabiowQuixada** [comment]
Hey @hbrice ,

version v5.23.0 adds "warning" and "info" levels to Isml Linter, please check the [docs](https://github.com/FabiowQuixada/isml-linter/blob/master/docs/generic-rule-config.md) and let me know if it works properly.

Thank you!

**Comment by hbrice** [comment]
This looks great!
