### ISSUE TITLE
Enforce Isprint rule.

### ISSUE THREAD

**Issue by sirenoxc** [FabiowQuixada/isml-linter#2]
For No Isscript rule there might be special cases like defining pageContext object in the template in decorators.
Suggestion: Rule can check that any pageContext object is assigned to a variable in isscript tags.

Enforce Isprint rule doesn't check if a variable is placed in html tag to be used for class names or etc.
Example: div class="${require('dw/web/Resource').msg('abc', '_classes', '')}" ></div
Suggestion: Rule can check the variable is written in a new line seperately.

No Inline Css rule doesn't check that inline style is used to define a dynamic css like backgroud colors.
Example: style="background-color: ${color.id}"
Suggestion: Rule can detects that style block has any ${} in it to be used as a variable.

**Comment by FabiowQuixada** [comment]
Hello @sirenoxc , thanks for your contribution!

Based on your requests, I've made some changes to Isml Linter:

1. It is possible now to disable specific rules for specific templates, so you can disable the "no-isscript" rule for templates that have "pt_" in its path, for example. Please check rule documentation for more information.
2. This is now fixed.
3. This seems to be working as expected, if you have another example, please let me know.

Once again, thanks!

**Comment by FabiowQuixada** [comment]
WIll close this issue for lack of activity.
