### ISSUE TITLE
Security improvement for links with target="_blank"

### ISSUE THREAD

**Issue by DenysArkan** [FabiowQuixada/isml-linter#20]
`rel="noopener"` should be added to links containing `target="_blank"` as a precaution against reverse tabnabbing. For more information, please refer to the following article:
https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

HTML: `<a href="http://example.com" target="_blank">Link</a>`
Fix: `<a href="http://example.com" target="_blank" rel="noopener">Link</a>`

**Comment by FabiowQuixada** [comment]
Hey @DenysArkan ,

thanks for the suggestion! I'll read about the topic and will let you know

Regards,

**Comment by FabiowQuixada** [comment]
Hey @DenysArkan ,

a new rule "[enforce-security](https://github.com/FabiowQuixada/isml-linter/blob/master/docs/rules/enforce-security.md)" is now available, covering the reverse tabnabbing security hole on version 5.27.0. Please confirm if it works as expected on your side and let me know.

If you have any other suggestion, please feel free to raise it!

Thank you,

**Comment by DenysArkan** [comment]
Thank you @FabiowQuixada
