### ISSUE TITLE
🔧 no-trailing-spaces	has wrong link in description

### ISSUE THREAD

**Issue by OleksandrMisiuga** [FabiowQuixada/isml-linter#21]
🔧 no-trailing-spaces | Disallows trailing blank spaces forwards to https://github.com/FabiowQuixada/isml-linter/blob/master/docs/rules/no-isscript.md

**Comment by FabiowQuixada** [comment]
Thanks for the tip, @OleksandrMisiuga ! The issue is now fixed.
Thanks!
