### ISSUE TITLE
Unexpected errors at linting

### ISSUE THREAD

**Issue by ClaudiuCudla** [FabiowQuixada/isml-linter#3]
Hello, 
I tried the linter and there's a reported issue:

![2019-06-06_14h01_36](https://user-images.githubusercontent.com/5812378/59066344-aac9c300-8863-11e9-9a5e-3474a25e9a8f.png)

This is one of the files it's failing at:
https://github.com/SalesforceCommerceCloud/storefront-reference-architecture/blob/master/cartridges/app_storefront_base/cartridge/templates/default/common/layout/checkout.isml

After adding them in the config for ignore, it just fails with exit code 1 with no other messages.

Thank you,

**Comment by FabiowQuixada** [comment]
Hello @ClaudiuCudla , thanks for the reporting.

The build issue regarding ignored files is now fixed. I'll investigate why those three files can't be parsed and will write here when a solution has been found.

Thank you,

**Comment by FabiowQuixada** [comment]
Hello again @ClaudiuCudla ,

version v5.14.1 should fix the parsing issues for those three templates.

Can you please confirm on your side?

Thank you!

**Comment by FabiowQuixada** [comment]
This issue will be closed for lack of activity.
