### ISSUE TITLE
Unexpected isapplepay element

### ISSUE THREAD

**Issue by ranveer5289** [FabiowQuixada/isml-linter#30]
Hello,

We are using isml-linter to lint our isml files and we see the below error when linting the files.

`Unexpected </isapplepay> element`

Below is the template code

```
        <isif condition="${(session.custom.applepaysession === 'yes') && (product.available && product.readyToOrder)}">
            <div class="col col-sm-6 pdp-apple-pay-button">
                <isapplepay class="apple-pay-pdp btn" sku="${product.id}"></isapplepay>
            </div>
        </isif>
```

isml-lint config

```
// Please check all available configurations and rules
// at https://www.npmjs.com/package/isml-linter.

var config = {
    rules: {
        'no-space-only-lines': {},
        'no-tabs': {},
        'no-trailing-spaces': {}
    }
};

module.exports = config;
```

For now, we have added the file under ignore list but I am interested if there is a better solution to handle this.

**Comment by FabiowQuixada** [comment]
Hello @ranveer5289 , thanks for reporting this issue.

I have investigated it and its fix is available in version 5.38.3, please update ISML Linter and let me know if it works as expected on your side.

Thank you!
