### ISSUE TITLE
Any possibility to have a verbose output?

### ISSUE THREAD

**Issue by aurelienlewin** [FabiowQuixada/isml-linter#31]
### Any possibility to have a verbose output option?

As sometimes the process gets somehow stuck, would this be possible to have a verbose mode option to know which file is being processed at the time being?

I tried `printPartialResults: true,` but it doesn't seem related to that.

**Comment by FabiowQuixada** [comment]
hey @aurelienlewin , thanks for the suggestion!

That's perfectly possible, I'll work on that and will let you know once it's ready.

Thanks!

**Comment by FabiowQuixada** [comment]
Hey @aurelienlewin ,

"verbose" option has been introduced to version 5.39.0, please update ISML Linter and let me know if it works as expected on your side.

You can check this option in [ISML Linter NPM page](https://www.npmjs.com/package/isml-linter).

Thanks!

**Comment by aurelienlewin** [comment]
<img width="291" alt="Screenshot 2021-09-20 at 09 44 21" src="https://user-images.githubusercontent.com/45093822/133970334-e4ab80b5-302e-4c9c-9932-dd9b71c36c35.png">
Awesome! 
Thanks to you, I now know why and when it fails and gets stuck. 
I'll have a deeper look now.

**Comment by aurelienlewin** [comment]
<img width="779" alt="Screenshot 2021-09-20 at 09 54 36" src="https://user-images.githubusercontent.com/45093822/133971338-4e7b5b3b-eb7c-4027-8554-5c0fb9f9ef1b.png">
Looks like it doesn't like that old shitty style inclusion within ISML markup.
Good news? Me neither.

**Comment by FabiowQuixada** [comment]
Hey @aurelienlewin ,

can you please provide that template in text format so I can investigate?

Thanks!

**Comment by FabiowQuixada** [comment]
Hey @aurelienlewin ,

can you please provide that template in text format so I can investigate?

Thanks!

**Comment by FabiowQuixada** [comment]
Hello @aurelienlewin ,

the issue has been fixed and it is now available in version 5.39.2. It was on the `div` element in line 35, which had a 2-level-deep `isif` tags embedded into it. You might see small indentation issues in that area, I hope I can solve those in the next few days.

Please let me know if you find any other issue.

Thanks!

**Comment by aurelienlewin** [comment]
Awesome! Good job.

**Comment by FabiowQuixada** [comment]
Hey @aurelienlewin , the indent issue is now fixed as well, please update ISML Linter to v5.39.3 and let me know if it works as expected on your side.

Once again, thanks for reaching out!

**Comment by aurelienlewin** [comment]
I'm not facing any issue about `isif` and `indent` with v5.39.3, thanks for keeping this linter up to date!

**Comment by FabiowQuixada** [comment]
Thanks Aurelien, I'm glad to help! :D

Based on your comment, I'll close this issue.

Thanks!
