### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by CodrutTapuOSF** [FabiowQuixada/isml-linter#35]
Hello @FabiowQuixada!

After i update the isml-linter to the latest version i have this issue when running both lint and fix. Downgrading to 5.39.3 seems to work. 

<img width="356" alt="Screen Shot 2022-02-15 at 9 23 49 AM" src="https://user-images.githubusercontent.com/48591770/154024723-d058699d-ac72-488c-9706-b381bd7790f3.png">

<img width="340" alt="Screen Shot 2022-02-15 at 9 23 53 AM" src="https://user-images.githubusercontent.com/48591770/154024711-241680ab-c695-4d83-9b08-db48918d3e86.png">

Thank you!

**Comment by FabiowQuixada** [comment]
hey @CodrutTapuOSF , thanks for reporting!

I was not able to reproduce the issue in my projects, can you please add `verbose: true` as a root-level attribute to the ISML Linter configuration file?

Also, please provide your ISML Linter configuration file as text (instead of an image) so I can investigate further

Thank you!

**Comment by CodrutTapuOSF** [comment]
Hello @FabiowQuixada,
I will start with my OS since i think this is the relevant information. I am using a MAC and i have this error on Github action too. Users with Windows don't have this issue.

Adding `verbose: true ` doesn't change things, the error is the same and with same information displayed.
Searching this error on the internet and found that it may occur when some files are saved using CRLF instead of LF

Please find below the config file

// Please check all available configurations and rules
// at https://www.npmjs.com/package/isml-linter.

module.exports = {
    rootDir: "./cartridges",
    verbose: true,
    ignore: [
    ],
    rules: {
        // Line by line rules;
        "enforce-require": {},
        "no-git-conflict": {},
        "no-import-package": {},
        "no-space-only-lines": {},
        "no-tabs": {},
        "no-trailing-spaces": {},

        // Tree rules;
        indent: {},
        "leading-iscontent": {},
        "no-embedded-isml": {},
        "no-hardcode": {
            except: ['(', ')', '[', ']', '"', '\'', '/', '+', '-', '*', ':', ',', '.']
        },
        "no-require-in-loop": {},
        "one-element-per-line": {},
        "leading-iscache": {},
        "no-deprecated-attrs": {},
        "contextual-attrs": {},
        "eslint-to-isscript": {},
        "no-iselse-slash": {},
        "empty-eof": {},
        "enforce-security": {},
    },
};

Thank you very much!

**Comment by CodrutTapuOSF** [comment]
@FabiowQuixada i uses this command `find ./ -type f -exec perl -pi -e 's/\r\n|\n|\r/\n/g' {} \;
` in order to convert CRLF to LF from the entire isml-linter directory and it worked properly after that.
I assume that this is the issue that needs to be fixed

**Comment by FabiowQuixada** [comment]
hey @CodrutTapuOSF , thanks for the info!

I will check this and will let you know

Thank you

**Comment by FabiowQuixada** [comment]
Hey @CodrutTapuOSF ! The issue should be fixed by now, can you please update ISML Linter to the latest version and let me know if it works as expected on your side?

Thanks!

**Comment by CodrutTapuOSF** [comment]
All good!
