### ISSUE TITLE
No support for custom web components

### ISSUE THREAD

**Issue by DenysArkan** [FabiowQuixada/isml-linter#37]
Hello. On one of the projects, i'm using web components embedded in ISML.

The functionality part is perfectly fine, however, the `isml-linter` seems to don't support usage of Web Components.

![image](https://user-images.githubusercontent.com/47108709/170928429-6712ed06-0298-482a-80d5-ec2532c76ac0.png)

Regards,

**Comment by FabiowQuixada** [comment]
Hello @DenysArkan !

Sorry for the late response, I will take a look at this. But I couldn't reproduce the issue, it seems it's not related to the line number you highlighted. Can you please provide the full file as text so I can test it as well?

Also, please let me know what ISML Linter version you are using, if it's not the latest, this issue might have been already fixed.

Please note that updating to the latest version, you might run into the issue mentioned [here](https://github.com/FabiowQuixada/isml-linter/issues/35), I'm currently in touch with Codrut (the issue reporter) to understand how to reproduce this one as well.

Please let me know if you need more information and thanks for reporting!

Regards,

**Comment by DenysArkan** [comment]
Thank you @FabiowQuixada . We are using:

- Node: 14.19.0
- isml-linter: 5.39.3 - because of issue `#35`

Just to isolate the issue, please see the code example:
```
<button type="button">
    <svg-icon icon="xmark" aria-hidden="true"></svg-icon>
</button>
```
Note: you are absolutely right, by making some tests and upgrading to 5.40.0 -> works well. So please feel free to close the issue.

**Comment by FabiowQuixada** [comment]
Hey @DenysArkan , the issue #35 should be fixed by now, can you please update ISML Linter to the latest version and let me know if it works as expected on your side?

Thanks!

**Comment by DenysArkan** [comment]
Thank you @FabiowQuixada. Works perfectly fine.
