### ISSUE TITLE
rootDir option is not working

### ISSUE THREAD

**Issue by ArthurZob** [FabiowQuixada/isml-linter#5]
Hello,
I'm trying to run isml-linter, on my project, and I need to use the rootDir option.
However, it's not working and it still using the path where I'm launching the command line.
In the file IsmlLinter.js line 152, I can see `pathData = pathData || config.rootDir;`, so the config is not used.
Is there a way to fix it ?
Regards,
Arthur

**Comment by FabiowQuixada** [comment]
Hello @ArthurZob ,

thanks for your feedback and for investigating the source of the issue. :)

This fix should be available very soon.

Thank you again!

**Comment by FabiowQuixada** [comment]
Hello @ArthurZob ,

the issue should be fixed now, under version 5.19.2, please check if it works as expected.

Thank you!

**Comment by ArthurZob** [comment]
Hello @fabioquixadaosf ,
Thank you for your quick fix :)
Regards,
Arthur
