### ISSUE TITLE
Whitelist instead of blacklist

### ISSUE THREAD

**Issue by ArthurZob** [FabiowQuixada/isml-linter#6]
Hello,
Is there a way to add a whitelist option, instead of ignore. (Maybe the ignore must be handled as the .eslintignore ?) ?
So we can only lint the file we want.
Regards,
Arthur

**Comment by FabiowQuixada** [comment]
Hello Arthur,
thanks for the suggestion, I will check the feasibility of adding that configuration option and get back to you.

Meanwhile, can you be a little more specific on what you need? 
In case you want to lint a specific file or a specific directory, it is perfectly feasiable to add an option to the command line, please let me know if that fits your needs.

Thanks!

**Comment by ArthurZob** [comment]
Hello @fabioquixadaosf ,
Actually, as for eslint, I want to watch specifics folders, but not only one.
And it's too long to lint all cartridges, and blacklist every directory that I don't want.
Let me know if you need more informations.
Regards,
Arthur

**Comment by FabiowQuixada** [comment]
Hey @ArthurZob ,
you mean something like `eslint file.js` via command line interface, right? If that's the case, that's what I mentioned in the first comment as a feasible solution.

If not, I couldn't find any attribute that can be added to a .eslintrc file that whitelists files to be linted. If such attribute exists, please let me know of it so I can check how it works and mimic its behavior.

Thank you!

**Comment by ArthurZob** [comment]
Hello @fabioquixadaosf ,
I'm not sure to understand, let me take an exemple, I have some cartridges :
A/
B/
C/
D/
E/

And I only want to watch the cartridges B/ and C/, how can I do this without ignoring A/, D/ and E/.

Regards,
Arthur

**Comment by FabiowQuixada** [comment]
Hey @ArthurZob ,
currently isml-linter doesn't support that, it will soon be available though line commands, such as: 

`isml-linter --autofix B/ C/`

Thank you!

**Comment by FabiowQuixada** [comment]
Hello @ArthurZob ,

version 5.21.0 has been released and linting specific files and directories is now possible.

Please update to the latest version, check the [CLI docs](https://github.com/FabiowQuixada/isml-linter/blob/HEAD/docs/cli.md) and let me know if that fits your needs.

Thank you!

**Comment by FabiowQuixada** [comment]
Will close this issue due to inactivity.
