### ISSUE TITLE
Rule "one-element-per-line" throws error for templates starting on <isif>

### ISSUE THREAD

**Issue by antondyachuk** [FabiowQuixada/isml-linter#7]
If template starts with **isif** instruction linter fires the error "one-element-per-line". Here is template example:
![image](https://user-images.githubusercontent.com/43670463/69728655-7c031a00-112d-11ea-995d-728cba03bc90.png)

**Comment by FabiowQuixada** [comment]
Hello @antondyachuk ,

thanks for reporting this issue! Will get back to you once it's fixed.

Thank you,

**Comment by FabiowQuixada** [comment]
Also, if you could provide a simplified version of that template that still reproduces the issue, it would be of great help!

**Comment by FabiowQuixada** [comment]
Hey @antondyachuk , the fix is now available on version 5.22.1, please update Isml Linter and let me know if it works as expected.

Thanks!

**Comment by antondyachuk** [comment]
Hi @FabiowQuixada 
It works within new version. Thanks!
