### ISSUE TITLE
Enhancement for rule "one-element-per-line" 

### ISSUE THREAD

**Issue by antondyachuk** [FabiowQuixada/isml-linter#8]
I have suggestion to make rule "one-element-per-line" more configurable so as to be able to disallow only tags to be on the same line but allow the text to be on the same line with wrapping tags.
Here example which currently is recognized as rule violation:
![image](https://user-images.githubusercontent.com/43670463/69728912-06e41480-112e-11ea-8add-e0580017b5b8.png)
I believe it makes sense to allow including text on the same line with tags. But multiple tags still should be forbidden:
![image](https://user-images.githubusercontent.com/43670463/69728997-3c88fd80-112e-11ea-99a0-5bb4afc389dc.png)

**Comment by FabiowQuixada** [comment]
Hello @antondyachuk , thanks for your suggestion. This feature is perfectly feasiable, will let you know once it's implemented.

Thank you!

**Comment by antondyachuk** [comment]
Hello @FabiowQuixada 
Thank you, looking forward for the new version

**Comment by FabiowQuixada** [comment]
Hello @antondyachuk ,

sorry for the delay, finally version 5.29.0 comes with the suggestion you prodided! Please take a look at ["one-element-per-line" rule documentation](https://github.com/FabiowQuixada/isml-linter/blob/HEAD/docs/rules/one-element-per-line.md) and let me know if it works as expected on your side.

Thanks!

**Comment by FabiowQuixada** [comment]
Closing due to inactitivity
