### ISSUE TITLE
Rule "empty-eof" is fired for templates ending with </isif> even if empty line is present

### ISSUE THREAD

**Issue by antondyachuk** [FabiowQuixada/isml-linter#9]
Here is example where rule  "empty-eof" triggers the error even if there is new line at the end of the file. I believe it happens because template ends with SFB2C tag:
![image](https://user-images.githubusercontent.com/43670463/69729236-a3a6b200-112e-11ea-93f6-f9376b817160.png)

**Comment by FabiowQuixada** [comment]
Thanks for reporting this issue @antondyachuk . Its fix should be available soon.

**Comment by FabiowQuixada** [comment]
Hey @antondyachuk , the fix is now available on version 5.22.1, please update Isml Linter and let me know if it works as expected.

Thanks!

**Comment by antondyachuk** [comment]
Hello @FabiowQuixada 
Thank you a lot, it works now!
